version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employeedb
    ports:
      - "3307:3306"
    networks:
      - employeenet

  spring-app:
    build: .
    container_name: spring-app
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    networks:
      - employeenet

networks:
  employeenet:
